### PR TITLE
Main

### PR DESCRIPTION
**Pull request by chimake**
Pulling and merging gitignore and linter configurations to the main branch

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @chimake,

# Status: Changes Required ♻️

I wish you a warm welcome to Microverse. Good job so far for implementing your first project!

There are some issues that you still need to work on to go to the next project but you are almost there!

A little bit more

## Good Highlights✔️

- Linter checks are passing
- Good commit messages


## Required Changes ♻️

1.  Describing pull requests is a good practice so that at a glance you and others can understand the changes contained there in. Kindly include one for this pull request. Access the menu options by clicking on the three-dot symbol at the top right corner of the pull request box.

image



2. Please, note that proper [GitHub flow as required](https://github.com/microverseinc/curriculum-transversal-skills/blob/9bf76d5f906c3db5f38b26577e52a260ef4191a5/documentation/hello_microverse_project.md?plain=1#L29) for this project expects that pull requests are made from a feature branch to the main branch and not vice versa. Kindly take note of this for future pull requests.

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chimake** [comment]
Hello @emmiiorji 
Thank you for the pointers they are quite helpful. I have added a descriptive comment as required, I have also taking note of the pull request flow. 

Question: Should I place another code review request? The task is marked as "change required" on my dashboard.

**Comment by emmiiorji** [comment]
Hi @chimake

Thank you for your response and taking note of the comments. Kindly request another review on your dashboard and the next reviewer will do justice.

**Comment by chimake** [comment]
I just did that. Thank you so much

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @chimake, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Top highlight 🎯

- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️

- [ ] As the previous reviewer has earlier suggested, your pull requests should be made from a feature branch to the main branch (GitHub flow) and not vice versa. 

In your case, your pull request should be made from `gitignore-lint-config` to `main `

This should be vice-versa 👇🏽 
image

Kindly watch this [video](https://www.youtube.com/watch?v=PrIY8sYwe90) to get more insights on how to follow GitHub flow 😄 
_Check the comments under the review._

## Optional suggestions

- Good job adding a pull request summary as suggested by the previous reviewer, In my opinion i will suggest you make sure that your comments are well descriptive, clear and easily understandable. You can use bullet points to itemize what you did in the project 👍🏽 

- I will also recommend you always write a well descriptive pull request title describing the feature or project you are working on. Instead of writing `Main` as your pull request title, you can write `Hello Microverse` or `LInter setup` which is more descriptive 😄 .

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chimake** [comment]
Thank you do much @vickymarz  for your guidance. I have adjusted the github flow accordingly.

**Review by brainconnect93 — COMMENTED** [review]
## Status: Approved :heavy_check_mark:

Hi @chimake, 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by joskalenda — COMMENTED** [review]
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @chimake , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
|  |

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
